# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 config.vm.define :servidor do |servidor|
 servidor.vm.box = "bento/ubuntu-22.04"
 servidor.vm.network :private_network, ip: "192.168.50.3"
 servidor.vm.hostname = "servidor"
 servidor.vm.provision "shell", path: "prometheus.sh"
 servidor.vm.provision "shell", path: "nodeExporter.sh"
 servidor.vm.provision "shell", path: "prueba.sh"
 end
end